# k3d configuration file, saved as e.g. /home/me/myk3dcluster.yaml
apiVersion: k3d.io/v1alpha3 # this will change in the future as we make everything more stable
kind: Simple # internally, we also have a Cluster config, which is not yet available externally
name: basic # name that you want to give to your cluster (will still be prefixed with )
servers: 1
agents: 0
kubeAPI: # same as  (where the name would resolve to 127.0.0.1)
  #host: gpu.louis030195.com # important for the  setting in the kubeconfig
  hostIP: "0.0.0.0" # where the Kubernetes API will be listening on
  hostPort: "6443" # where the Kubernetes API listening port will be mapped to on your host system
image: registry.gitlab.com/vainkop1/k3s-gpu:v1.21.2-k3s1
ports:
  - port: 80:80 # same as `--port '80:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
        #- port: 30000-32767:30000-32767
        # nodeFilters:
        #- server:*
options:
  runtime: # runtime (docker) specific options
    gpuRequest: all # same as `--gpus all`
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments pasised to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: "--tls-san=my.host.domain"
        nodeFilters:
          - server:*

