# helm repo add gpu-helm-charts https://nvidia.github.io/dcgm-exporter/helm-charts
# helm repo update
# helm install nvidia gpu-helm-charts/dcgm-exporter -n nvidia --create-namespace
# helm repo add nvdp https://nvidia.github.io/k8s-device-plugin
# helm repo update
# helm install nvidia-device-plugin nvdp/nvidia-device-plugin -n nvidia --create-namespace -f values.nvidia.yaml
# helm uninstall nvidia-device-plugin -n nvidia
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gpu2
          - louis-gpu
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gpu2
          - louis-gpu
