functionNamespace: openfaas-fn
generateBasicAuth: true
ingress:
  enabled: true
  # Used to create Ingress record (should be used with exposeServices: false).
  hosts:
    - host: openfaas.louis030195.com  # Replace with gateway.example.com if public-facing
      serviceName: gateway
      servicePort: 8080
      path: /
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-prod
  tls:
    - hosts:
        - openfaas.louis030195.com
      secretName: openfaas-crt

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - intel
                - amd64